"""empty message

Revision ID: 11fcca38b0d7
Revises: 
Create Date: 2017-05-27 09:33:55.340872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fcca38b0d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('headline', sa.String(), nullable=True))
    op.drop_column('articles', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('articles', 'headline')
    # ### end Alembic commands ###
