"""empty message

Revision ID: 3640c468daaa
Revises: c729e9b55bd1
Create Date: 2017-05-28 21:36:26.845325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3640c468daaa'
down_revision = 'c729e9b55bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('aws_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'articles', ['aws_url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'aws_url')
    # ### end Alembic commands ###
