"""empty message

Revision ID: 4cdcccc2f4d0
Revises: 3640c468daaa
Create Date: 2017-05-28 22:13:17.521948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdcccc2f4d0'
down_revision = '3640c468daaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('target_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'articles', ['target_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    op.drop_column('articles', 'target_name')
    # ### end Alembic commands ###
