"""empty message

Revision ID: 95d9ae98b2da
Revises: 
Create Date: 2017-05-29 03:20:20.261239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d9ae98b2da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_name', sa.String(), nullable=True),
    sa.Column('raw_url', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=True),
    sa.Column('aws_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aws_url'),
    sa.UniqueConstraint('headline'),
    sa.UniqueConstraint('raw_url'),
    sa.UniqueConstraint('target_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
