"""empty message

Revision ID: a8e0ab6c5f30
Revises: 95d9ae98b2da
Create Date: 2017-05-30 18:12:20.506221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e0ab6c5f30'
down_revision = '95d9ae98b2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_raw_url_key', 'articles', type_='unique')
    op.drop_column('articles', 'raw_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('raw_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('articles_raw_url_key', 'articles', ['raw_url'])
    # ### end Alembic commands ###
